[project]
name = "ffhs-dua"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "jupyter>=1.1.1",
    "pytest>=8.4.1",
    "ruff>=0.12.10",
]
